def check_vowels():
	name = input("Ingrese su nombre:").lower()
	name = name.replace("á","a")
	name = name.replace("í","i")
	name = name.replace("é","e")
	name = name.replace("ó","o")
	name = name.replace("ú","u")
	name = name.replace("ü","u")
	print(f"Contiene a: {"a" in name }")
	print(f"Contiene e: {"e" in name }")
	print(f"Contiene i: {"i" in name }")
	print(f"Contiene o: {"o" in name }")
	print(f"Contiene u: {"u" in name }")
